version: '2'
networks:
    traefik_default:
        external: true
services:
    node:
        image: node
        volumes:
            - ${HEXO_SOURCE_CODE}:/code
        ports:
            - 4000:4000
        tty: true
    nginx:
        build:
            context: .
            dockerfile: ./nginx/Dockerfile
            args:
                DOMAIN: ${DOMAIN}
        volumes:
            - ../hexo:/code
        networks:
            - traefik_default
        labels:
            - traefik.http.routers.hexo.rule=HOST(`${DOMAIN}`)
        tty: true
