version: '2'
networks:
    traefik_default:
        external: true
services:
    node:
        image: node
        volumes:
            - ../hexo:/code
        ports:
            - 4000:4000
        tty: true
    nginx:
        build:
            context: .
            dockerfile: ./nginx/Dockerfile
        volumes:
            - ../hexo:/code
        networks:
            - traefik_default
        labels:
            - traefik.http.routers.hexo.rule=HOST(`myhexo.com`)
        tty: true
